version: "3"

services:
  jp:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ssh:/root/.ssh
      - logs:/root/log
    environment:
      GIT_USERNAME: "dooteeen"
      GIT_EMAIL: "do2te3n@gmail.com"
      BUCKET: "dooteeen/scoop-for-jp"
      REMOTE_HOST: "github.com"
      CRONTAB: "20 4 * * *"
volumes:
  ssh:
  logs:
