version: "3"

services:
  jp:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ssh:/root/.ssh
      - logs:/root/log
    environment:
      GIT_USERNAME: "rkbk60"
      GIT_EMAIL: "b8csmlplg@gmail.com"
      BUCKET: "rkbk60/scoop-for-jp"
      REMOTE_HOST: "bitbucket.org"
      CRONTAB: "20 4 * * *"
volumes:
  ssh:
  logs:
